import sys
from PySide6 import QtWidgets as qtw
import requests

# importing the UI class generated by Qt Designer
from UI.ui_find_orders_window import Ui_find_order_form

class FindOrder(qtw.QWidget,Ui_find_order_form):
    """
    A class for the Find Order window in the application.

    Inherits from QWidget and the Ui_find_order_form class generated by Qt Designer.
    """    
    def __init__(self):
        """
        Initialize the Find Order window.

        Sets up the UI and connects the buttons to their corresponding functions.
        """        
        super().__init__()
        self.setupUi(self)
        # Set the width of each column in the orders table
        self.orders_table.setColumnWidth(0,75)
        self.orders_table.setColumnWidth(1,130)
        self.orders_table.setColumnWidth(2,135)
        self.orders_table.setColumnWidth(3,235)
        self.orders_table.setColumnWidth(4,235)
        self.orders_table.setColumnWidth(5,100)
        # Connecting buttons to their functions
        self.search_button.clicked.connect(self.find_order)
        self.select_button.clicked.connect(self.open_order_information)
        self.clear_button.clicked.connect(self.clear_products)

    def find_order(self):
        """
        Find orders with a customer name matching the input text.

        Retrieves data from the API and populates the orders table with the data.
        """        
        # getting the customer name from the customer name entry box
        name = self.customer_name_box.text()
        url = f"http://localhost:5000/api/order/{name}"
        response = requests.get(url)
        if response.status_code == 200:
            orders_list = response.json()
            row = 0 
            # setting the row count to the number of orders in the order list 
            self.orders_table.setRowCount(len(orders_list))
            # print(orders_list)
            for order in orders_list:
                # Creating table items for each order attribute
                customer_name = qtw.QTableWidgetItem(order["customer_name"])
                customer_address = qtw.QTableWidgetItem(order["customer_address"])
                created = qtw.QTableWidgetItem(order["created"])
                completed = qtw.QTableWidgetItem(str(order['completed']))
                order_id = qtw.QTableWidgetItem(str(order["order_id"]))
                processed = qtw.QTableWidgetItem(order["processed"])
                # Setting the table items in the corresponding row and column
                self.orders_table.setItem(row, 0, order_id)
                self.orders_table.setItem(row, 1, customer_name)
                self.orders_table.setItem(row, 2, customer_address)
                self.orders_table.setItem(row,3,processed)
                self.orders_table.setItem(row, 4, created)
                self.orders_table.setItem(row, 5, completed)
                row = row + 1
        else:
            print("Failed to retrieve products")    

    def open_order_information(self):
        """
        Open the selected order and display its products.

        Retrieves data from the API and populates the products table with the data.
        """     
        # Getting the ID of the selected order   
        selected_row = self.orders_table.currentRow()
        order_id = self.orders_table.item(selected_row, 0).text()
        # print(order_id)
        response = requests.get(f"http://localhost:5000/api/order/{order_id}")
        if response.status_code == 200:
            order_list = response.json()
            # print(order_list)
            row = 0 
            self.products_table.setRowCount(len(order_list["products"]))
            self.total_price_box.setText(str(order_list["price"]))
            # Displaying the order's products in the products table
            for product in order_list["products"]:
                name_item = qtw.QTableWidgetItem(product["name"])
                price_item = qtw.QTableWidgetItem(str(product["price"]))
                quantity_item = qtw.QTableWidgetItem(str(product["quantity"]))
                self.products_table.setItem(row, 0, name_item)
                self.products_table.setItem(row, 1, price_item)
                self.products_table.setItem(row, 2, quantity_item)
                row = row + 1                 
            print('Request was successful')
        else:
            print('Request failed with status code:', response.status_code)

    def clear_products(self):
        """
        Clear the products and orders table and total price box.
        """  
        # clearing all the entries and the table contents        
        self.products_table.setRowCount(0)
        self.total_price_box.clear()
        self.customer_name_box.clear()
        self.orders_table.setRowCount(0)

if __name__ == "__main__":
   # Creating the application instance   
   app = qtw.QApplication(sys.argv)

   # Creating and show the product list widget
   window = FindOrder()
   window.show()
   # Starting the application event loop    
   sys.exit(app.exec())